version: '3'

services:
  postgres:
    container_name: python_db
    image: healthcheck/postgres:alpine
    environment:
      - POSTGRES_USER=db_python_user
      - POSTGRES_DB=db_python_project
      - POSTGRES_PASSWORD=7*Python369
    networks:
        backend-py-net:
            ipv4_address: 21.21.112.5
  server:
    build:    
      context: ./
      dockerfile: Dockerfile
    container_name: python_server
    ports:
      - 8007:8007
    environment:
      DATABASE_URL: postgres://db_python_user@postgres/db_python_project
    networks:
        backend-py-net:
            ipv4_address: 21.21.112.4
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
    tty: true
    #command: python app.py

networks:
    backend-py-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 21.21.112.0/26
